package de.erdbeerbaerlp.discordrpc;

import de.erdbeerbaerlp.discordrpc.Message_Icon.ICOReceiveHandler;
import de.erdbeerbaerlp.discordrpc.Message_Message.MSGReceiveHandler;
import de.erdbeerbaerlp.discordrpc.RequestMessage.CommunicationMessageHandler;
import net.minecraft.client.Minecraft;
import net.minecraftforge.client.ClientCommandHandler;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.minecraftforge.fml.relauncher.Side;

import java.time.Instant;

@Mod(modid = ModClass.MODID, name = ModClass.NAME, version = ModClass.VERSION, dependencies = "required-after-client:eguilib", canBeDeactivated = false, acceptedMinecraftVersions = "[1.12,1.12.2]", acceptableRemoteVersions = "*", guiFactory = "de.erdbeerbaerlp.discordrpc.CfgGuiFactory", updateJSON = "http://erdbeerbaerapi.tk/discordrpc.json")
public class ModClass {
    /**
     * Mod ID
     */
    public static final String MODID = "discordrpc";
    /**
     * Mod Version
     */
    public static final String VERSION = "1.3";
    /**
     * Mod Name (What did you expect?)
     */
    public static final String NAME = "DiscordRichPresence";
    /**
     * The timestamp where the game was launched
     */
    public static final long gameStarted = Instant.now().getEpochSecond();
    protected static final SimpleNetworkWrapper REQUEST = NetworkRegistry.INSTANCE.newSimpleChannel("DiscordReq");
    protected static final SimpleNetworkWrapper MSG = NetworkRegistry.INSTANCE.newSimpleChannel("DiscordMSG");
    protected static final SimpleNetworkWrapper ICO = NetworkRegistry.INSTANCE.newSimpleChannel("DiscordIcon");
    protected static boolean isEnabled = true;
    protected static boolean isClient = true;
    protected static boolean logtochat = false;
    protected static boolean preventConfigLoad = false;

    @EventHandler
    public void modConstruction(FMLConstructionEvent evt) {
        System.out.println("Constructing");
        if (evt.getSide() == Side.CLIENT) {
            DRPCLog.Info("Running on Client side... starting");
            isClient = true;
            if (!preventConfigLoad) RPCconfig.loadConfigFromFile();
            DRPCLog.Debug("Player UUID is " + Minecraft.getMinecraft().getSession().getPlayerID());
            REQUEST.registerMessage(CommunicationMessageHandler.class, RequestMessage.class, 0, Side.SERVER);
            MSG.registerMessage(MSGReceiveHandler.class, Message_Message.class, 1, Side.CLIENT);
            ICO.registerMessage(ICOReceiveHandler.class, Message_Icon.class, 1, Side.CLIENT);
            if (isEnabled) Discord.initDiscord();
            if (!preventConfigLoad) RPCconfig.loadConfigFromFile();
            Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                DRPCLog.Info("Shutting down DiscordHook.");
                Discord.shutdown();
            }));

            if (isEnabled) Discord.setPresence(RPCconfig.NAME, "Starting game...", "34565655649643693");
        } else {
            isClient = false;
            DRPCLog.Info("Loading serverside stuff...");
            ServerConfig.preInit();
            REQUEST.registerMessage(CommunicationMessageHandler.class, RequestMessage.class, 0, Side.SERVER);
            MSG.registerMessage(MSGReceiveHandler.class, Message_Message.class, 1, Side.CLIENT);
            ICO.registerMessage(ICOReceiveHandler.class, Message_Icon.class, 1, Side.CLIENT);

        }
    }

    @EventHandler
    public void preInit(FMLPreInitializationEvent evt) {
        ModMetadata meta = evt.getModMetadata();
        meta.autogenerated = false;
        meta.modId = MODID;
        meta.name = NAME;
        meta.authorList.add("ErdbeerbaerLP");
        meta.description = "Gives you an nice discord rich presence";
        meta.version = VERSION;
        meta.url = "https://minecraft.curseforge.com/projects/discordrichpresence";
        meta.updateJSON = "http://erdbeerbaerapi.tk/discordrpc.json";
        if (isClient && isEnabled) {
            MinecraftForge.EVENT_BUS.register(DRPCEventHandler.class);
            ClientCommandHandler.instance.registerCommand(new Command());

        }
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {


        if (isClient && isEnabled) {
            Discord.setPresence(RPCconfig.NAME, "Starting game...", "3454083453475893469");
        }

    }

    @EventHandler
    public void starting(FMLServerStartingEvent e) {
        e.registerServerCommand(new ServerCommand());
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent evt) {
    }
}
